#!/usr/bin/env python3
import Main
import Reglas

base_de_hechos = []
areas = {
	#Fila1
	# Fila1
	'AireLibre011': ['Observar a la gente cuando viajo','Observar el paisaje cuando viajo','Observar las cosechas cuando viajo'],
	'Calculo012': ['Leer las lecciones a un ciego','Tomar nota del transito que pasa por cierto punto','Interrogar a la gente en una encuesta de opinion publica'],
	'Persuasivo012': ['Leer las lecciones a un ciego','Tomar nota del transito que pasa por cierto punto','Interrogar a la gente en una encuesta de opinion publica'],
	'ServicioSocial012': ['Leer las lecciones a un ciego','Tomar nota del transito que pasa por cierto punto','Interrogar a la gente en una encuesta de opinion publica'],
	'AireLibre013': ['Participar en las diversiones de una feria','Contemplar la exposicion de productos envasados en una feria','Contemplar la exposicion de productos naturales en una feria'],
	'AireLibre014': ['Realizar ejercicios en un gimnasio','Ir de pesca','Jugar futbol'],
	'AireLibre015': ['Hojeas libros en una biblioteca','Asistir a un concierto de una orquesta','Visitar un acuario'],
	'AireLibre016': ['Coleccionar autografos de gente famosa','Coleccionar mariposas','Coleccionar trozos de diferentes clases de madera'],
	'Cientifico017': ['Visitar una exposicion de pintura','Visitar una exposicion de diferentes medios de transporte','Visitar una exposicion de equipos de laboratorio'],
	'AireLibre018': ['Vender verduras','Ser musico organista','Cultivar verduras'],
	'Persuasivo018': ['Vender verduras','Ser musico organista','Cultivar verduras'],
	'Musical018': ['Vender verduras','Ser musico organista','Cultivar verduras'],
	'Oficina019': ['Ser el presidente de la Junta Directiva de un club de baile','Decorar el salon de baile','Enviar folletos de anuncio del baile'],
	'Mecanico010': ['Visitar un museo pintura','Visitar una agencia de publicidad','Visitar una fabrica de maquinas de escribir'],
	'Cientifico010': ['Visitar un museo pintura','Visitar una agencia de publicidad','Visitar una fabrica de maquinas de escribir'],
	'Persuasivo010': ['Visitar un museo pintura','Visitar una agencia de publicidad','Visitar una fabrica de maquinas de escribir'],
	
	#Fila2
	'Mecanico021': ['Leer una novela a una persona enferma','Enseñar a un perro a hacer habilidades','Desarmar un juguete malogrado e intentar arreglarlo'],
	'Mecanico022': ['Seguir un curso de dibujo','Seguir un curso de biologia','Seguir un curso de trabajo en metal'],
	'Artistico022': ['Seguir un curso de dibujo','Seguir un curso de biologia','Seguir un curso de trabajo en metal'],
	'Artistico023': ['Construir viviendas para pajaros','Escribir articulos a cerca de los pajaros','Hacer dibujos de pajaros'],
	'Mecanico024': ['Arreglar una maquina de coser','Tocar piano','Dibujar o pintar una escena interesante'],
	'Artistico024': ['Arreglar una maquina de coser','Tocar piano','Dibujar o pintar una escena interesante'],
	'Musical024': ['Arreglar una maquina de coser','Tocar piano','Dibujar o pintar una escena interesante'],
	'AireLibre025': ['Escuchar un programa de radio sobre el cultivo de frutos','Escuchar un programa de radio sobre trabajos plasticos','Escuchar un programa de radio sobre como fotografiar animales salvajes'],
	'AireLibre026': ['Colaborar en un periodico escribiendo en la pagina dedicada a resolver problemas personales','Criar perros de raza','Dirigir estudios a cerca de la efectividad de los diferentes tipos de cartas comerciales'],
	'AireLibre027': ['Ser un experto en el juego de cartas','Ser una autoridad en erosion del suelo (desgaste del terreno por accion de las aguas, vientos, etc.)','Ser un experto en propaganda comercial'],
	'Persuasivo027': ['Ser un experto en el juego de cartas','Ser una autoridad en erosion del suelo (desgaste del terreno por accion de las aguas, vientos, etc.)','Ser un experto en propaganda comercial'],
	'AireLibre028': ['Visitar un estudio de cine','Visitar un bosque famoso por sus perspectivas de montanas','Visitar un antiguo campo de batalla'],
	'AireLibre029': ['Informarme mediante la lectura, de las actividades realizadas por hombres famosos de su vida publica','Leer las descripciones de diferentes escritores acerca de lo que seria un mundo ideal','Leer acerca de la vida de los fundadores del pais'],
	'AireLibre020': ['Aconsejar a la gente acerca de como mejorar sus personalidades','Cazar animales salvajes','Pagar o hacer efectivos los cheques de un banco'],
	'Oficina020': ['Aconsejar a la gente acerca de como mejorar sus personalidades','Cazar animales salvajes','Pagar o hacer efectivos los cheques de un banco'],
	'Cientifico020': ['Aconsejar a la gente acerca de como mejorar sus personalidades','Cazar animales salvajes','Pagar o hacer efectivos los cheques de un banco'],
	
	#Fila 3
	'ServicioSocial031': ['Pertenecer a un grupo en el que se discutan problemas de la vida moderna', 'Pertenecer a un club literario', 'Pertenecer a un club astronomico de aficionados'],
	'ServicioSocial032': ['Relacionarme con gente corriente, de tipo medio', 'Relacionarme con gente un tanto extrana y que tiene ideas originales', 'Relacionarme con gente despreocupada cuya conducta atraiga la atencion'],
	'Persuasivo033': ['Dar clases de espanol a personas que aspiran obtener la ciudadania boliviana', 'Ser agente comercial bancario', 'Ser jefe de cocina de un restaurante de categoria'],
	'ServicioSocial033': ['Desarrollar nuevas variedades de flores', 'Dirigir campanas de anuncio para floristas', 'Tomar los encargos telefonicos en una tienda de flores'],
	'Oficina034': ['Ser el director de un grupo de investigaciones sobre metodos de propaganda', 'Ser el director de un programa academico en la universidad', 'Ser experto en fotografia a color'],
	'Persuasivo035': ['Hacer los dibujos para una historia del mundo', 'Cultivar una variedad de duraznos sin pepa', 'Entrenar a un grupo de aspirantes a un primer puesto en una competencia de arte dramatico'],
	'Artistico035': ['Pagar una parte de mis gastos en el colegio, ayudando en el laboratorio', 'Pagar una parte de mis gastos en el colegio, calificando los examenes', 'Pagar una parte de mis gastos en el colegio, formando parte de la orquesta'],
	'Cientifico036': ['Escribir una historia de la Cruz Roja', 'Buscar alguna informacion que pueda arrojar una nueva luz sobre un hecho historico famoso', 'Escribir una comedia musical'],
	'Artistico036': ['Ensenar espanol', 'Recibir las llamadas telefonicas de pedidos de mercancia', 'Pedir por telefono opinion a la gente para una encuesta'],
	'Cientifico037': ['Comprar mercancias al por mayor para venderlas en las grandes tiendas', 'Entrevistar a la gente que aspira obtener un empleo en grandes tiendas', 'Criar ganado vacuno'],
	'Musical037': ['Pertenecer a un grupo en el que se discutan problemas de la vida moderna', 'Pertenecer a un club literario', 'Pertenecer a un club astronomico de aficionados'],
	'Oficina037': ['Relacionarme con gente corriente, de tipo medio', 'Relacionarme con gente un tanto extrana y que tiene ideas originales', 'Relacionarme con gente despreocupada cuya conducta atraiga la atencion'],
	'Cientifico038': ['Dar clases de espanol a personas que aspiran obtener la ciudadania boliviana', 'Ser agente comercial bancario', 'Ser jefe de cocina de un restaurante de categoria'],
	'Musical038': ['Desarrollar nuevas variedades de flores', 'Dirigir campanas de anuncio para floristas', 'Tomar los encargos telefonicos en una tienda de flores'],
	'Persuasivo039': ['Ser el director de un grupo de investigaciones sobre metodos de propaganda', 'Ser el director de un programa academico en la universidad', 'Ser experto en fotografia a color'],
	'Oficina039': ['Hacer los dibujos para una historia del mundo', 'Cultivar una variedad de duraznos sin pepa', 'Entrenar a un grupo de aspirantes a un primer puesto en una competencia de arte dramatico'],
	'AireLibre030': ['Pagar una parte de mis gastos en el colegio, ayudando en el laboratorio', 'Pagar una parte de mis gastos en el colegio, calificando los examenes', 'Pagar una parte de mis gastos en el colegio, formando parte de la orquesta'],
	
			# RPARTE ANDREA
	#Fila4

	'AireLibre041': ['Encargarme de contratar personal en un trabajo','Escribir articulos sobre animales salvajes', 'Colaborar en un periodico escribiendo en la pagina dedicada a consejos personales'],
	'AireLibre042': ['Informarme mediante la lectura, de los metodos modernos a emplear en negocios','Leer acerca de las costumbres de las gentes de otros paises','Leer acerca de los modernos metodos empleados en granjas'],
	'AireLibre043': ['Trabajar en una estacion meteorologica en el Artico','Trabajar en una estacion meteorologica en la ciudad','Trabajar en una estacion meteorologica en la montana'],
	'Cientifico044': ['Ser muy conocido como director de una investigacion cientifica','Ser muy conocido como sociologo','Ser muy conocido como critico literario'],
	'Literario044': ['Ser muy conocido como director de una investigacion cientifica','Ser muy conocido como sociologo','Ser muy conocido como critico literario'],
	'ServicioSocial044': ['Ser muy conocido como director de una investigacion cientifica','Ser muy conocido como sociologo','Ser muy conocido como critico literario'],
	'Cientifico045': ['Realizar el decorado de una obra teatral','Hacer el analisis quimico de una nueva pasta de dientes','Escribir un articulo para las amas de casa sobre aspectos domesticos'],
	'ServicioSocial046': ['Entrevistar a candidatos tratando de ayudarlos','Probar diferentes cartas comerciales para ver que tipo resulta mejor','Trabajar en el desarrollo de los metodos mas eficientes de trabajo en una oficina'],
	'Oficina046': ['Entrevistar a candidatos tratando de ayudarlos','Probar diferentes cartas comerciales para ver que tipo resulta mejor','Trabajar en el desarrollo de los metodos mas eficientes de trabajo en una oficina'],
	'Cientifico047': ['Redactar noticias bancarias para un periodico','Trabajar en el perfeccionamiento de un metal','Organizar una ciudad modelo para los trabajadores de una fabrica'],
	'ServicioSocial047': ['Redactar noticias bancarias para un periodico','Trabajar en el perfeccionamiento de un metal','Organizar una ciudad modelo para los trabajadores de una fabrica'],
	'Oficina047': ['Redactar noticias bancarias para un periodico','Trabajar en el perfeccionamiento de un metal','Organizar una ciudad modelo para los trabajadores de una fabrica'],
	'Cientifico048': ['Visitar un museo de arte','Visitar un centro de recreo para la gente pobre','Visitar un laboratorio famoso de investigaciones medicas'],
	'ServicioSocial048': ['Visitar un museo de arte','Visitar un centro de recreo para la gente pobre','Visitar un laboratorio famoso de investigaciones medicas'],
	'Cientifico049': ['Ser el encargado de despedir a los empleados no aptos en una compania','Ser el encargado de hablar a los empleados que no realizan un buen trabajo','Ser el encargado de contratar nuevos empleados en una compania'],
	'Cientifico040': ['Recopilar un diccionario de expresiones familiares', 'Descubrir un medicamento contra el asma','Aplicar metodos que signifiquen mejora en un negocio'],
	'ServicioSocial040': ['Recopilar un diccionario de expresiones familiares', 'Descubrir un medicamento contra el asma','Aplicar metodos que signifiquen mejora en un negocio'],
	'Oficina040': ['Recopilar un diccionario de expresiones familiares', 'Descubrir un medicamento contra el asma','Aplicar metodos que signifiquen mejora en un negocio'],
	


 #Fila5

	'Cientifico051': ['Hacer Estudios sobre la historia del drama teatral','Hacer Estudios sobre las primitivas formas musicales','Realizar experimentos sobre el efecto del lenguaje en la conducta'],
	'Musical051': ['Hacer Estudios sobre la historia del drama teatral','Hacer Estudios sobre las primitivas formas musicales','Realizar experimentos sobre el efecto del lenguaje en la conducta'],
	'Cientifico052': ['Hacer analisis quimicos de nuevos productos comerciales','Trabajar en el perfeccionamiento del pulmon artificial','Construir graficas que muestren la marcha del negocio'],
	'Oficina052': ['Hacer analisis quimicos de nuevos productos comerciales','Trabajar en el perfeccionamiento del pulmon artificial','Construir graficas que muestren la marcha del negocio'],
	'Persuasivo053': ['Poner volantes de propaganda en los autos estacionados','Contar el numero de autos que pasen por una esquina a diferentes horas','Dirigir el transito en una esquina'],
	'AireLibre054': ['Dar clases de gimnasia a ninos invalidos','Cultivar verduras para el mercado','Dar clases de cesteria y telar'],
	'Persuasivo055': ['Solicitar dinero para los fondos de una institucion','Escribir el reportaje diario del progreso economico de la institucion','Hacer una relacion de los gastos de una institucion'],
	'Literario055': ['Solicitar dinero para los fondos de una institucion','Escribir el reportaje diario del progreso economico de la institucion','Hacer una relacion de los gastos de una institucion'],
	'Oficina055': ['Solicitar dinero para los fondos de una institucion','Escribir el reportaje diario del progreso economico de la institucion','Hacer una relacion de los gastos de una institucion'],
	'Literario056': ['Encargarme de los preparativos de una boda de lujo','Enviar las invitaciones para una boda de lujo','Escribir una cronica de una boda de lujo'],
	'Oficina056': ['Encargarme de los preparativos de una boda de lujo','Enviar las invitaciones para una boda de lujo','Escribir una cronica de una boda de lujo'],
	'Literario057': ['Escribir novelas','Dirigir una investigacion sobre la psicologia de la musica', 'Fabricar objetos de ceramica'],
	'AireLibre058': ['Dirigir una investigacion sobre la efectividad de los diferentes tipos de ventas','Separar en grupos las cartas en una oficina de correos','Criar pollos'],
	'Persuasivo058': ['Dirigir una investigacion sobre la efectividad de los diferentes tipos de ventas','Separar en grupos las cartas en una oficina de correos','Criar pollos'],
	'Oficina058': ['Dirigir una investigacion sobre la efectividad de los diferentes tipos de ventas','Separar en grupos las cartas en una oficina de correos','Criar pollos'],
	'Cientifico059': ['Escribir en la pagina de sucesos del periodico','Dar conferencias populares sobre quimica','Orientar a la gente joven sobre la eleccion de una carrera'],
	'Literario059': ['Escribir en la pagina de sucesos del periodico','Dar conferencias populares sobre quimica','Orientar a la gente joven sobre la eleccion de una carrera' ],
	'ServicioSocial059': ['Escribir en la pagina de sucesos del periodico','Dar conferencias populares sobre quimica','Orientar a la gente joven sobre la eleccion de una carrera'],
	'ServicioSocial050': ['Tener a alguien que tome siempre mis decisiones por mi','Tener a alguien que tome mis decisiones en alguna ocasion','Tomar siempre mis decisiones por mi mismo'],
	



 #Fila6

	'Cientifico061': ['Vigilar una seccion de una tienda grande','Dirigir una investigacion sobre television','Ser el director de un centro de recreo en una organizacion de beneficencia'],
	'Persuasivo061': ['Vigilar una seccion de una tienda grande','Dirigir una investigacion sobre television','Ser el director de un centro de recreo en una organizacion de beneficencia'],
	'ServicioSocial061': ['Vigilar una seccion de una tienda grande','Dirigir una investigacion sobre television','Ser el director de un centro de recreo en una organizacion de beneficencia'],
	'Oficina061': ['Vigilar una seccion de una tienda grande','Dirigir una investigacion sobre television','Ser el director de un centro de recreo en una organizacion de beneficencia'],
	'Persuasivo062': ['Vigilar el trabajo de varias mecanografas','Entrevistar a la gente que aspira a obtener un empleo','Ser secretario privado'],
	'Oficina062': ['Vigilar el trabajo de varias mecanografas','Entrevistar a la gente que aspira a obtener un empleo','Ser secretario privado'],
	'AireLibre063': ['Dibujar una historieta comica','Dirigir la propaganda introductoria de aparatos','Administrar una granja agricola'],
	'Persuasivo063': ['Dibujar una historieta comica','Dirigir la propaganda introductoria de aparatos','Administrar una granja agricola'],
	'Artistico063': ['Dibujar una historieta comica','Dirigir la propaganda introductoria de aparatos','Administrar una granja agricola'],
	'Cientifico064': ['Intentar hacer algun dulce del que no se la receta','Contar cuentos a los ninos','Pintar con acuarelas'],
	'Artistico064': ['Intentar hacer algun dulce del que no se la receta','Contar cuentos a los ninos','Pintar con acuarelas'],
	'ServicioSocial064': ['Intentar hacer algun dulce del que no se la receta','Contar cuentos a los ninos','Pintar con acuarelas'],
	'Cientifico065': ['Hacer investigaciones quimicas','Entrevistar a los aspirantes a algun empleo','Escribir cuentos en algun periodico'],
	'Oficina065': ['Hacer investigaciones quimicas','Entrevistar a los aspirantes a algun empleo','Escribir cuentos en algun periodico'],
	'Mecanico066': ['Dibujar o pintar una escena interesante','Probar diferentes tipos de velas en un velero de juguete para ver cual funciona mejor','Escribir un ensayo sobre el estilo literario de cierto autor'],
	'Cientifico066': ['Dibujar o pintar una escena interesante','Probar diferentes tipos de velas en un velero de juguete para ver cual funciona mejor','Escribir un ensayo sobre el estilo literario de cierto autor'],
	'Artistico066': ['Dibujar o pintar una escena interesante','Probar diferentes tipos de velas en un velero de juguete para ver cual funciona mejor','Escribir un ensayo sobre el estilo literario de cierto autor'],
	'Calculo067': ['Vender entradas para una presentacion teatral de aficionados','Preparar el programa para la presentacion','Actuar como tesorero en la presentacion'],
	'Persuasivo067': ['Vender entradas para una presentacion teatral de aficionados','Preparar el programa para la presentacion','Actuar como tesorero en la presentacion'],
	'Calculo068': ['Determinar el costo de la produccion de un nuevo invento para lavar platos','Convencer a alguien para que financie a la compania que lanzara un invento para lavar platos','Ensenar a la gente a usar el lavaplatos'],
	'Persuasivo068': ['Determinar el costo de la produccion de un nuevo invento para lavar platos','Convencer a alguien para que financie a la compania que lanzara un invento para lavar platos','Ensenar a la gente a usar el lavaplatos'],
	'ServicioSocial068': ['Determinar el costo de la produccion de un nuevo invento para lavar platos','Convencer a alguien para que financie a la compania que lanzara un invento para lavar platos','Ensenar a la gente a usar el lavaplatos'],
	'Calculo069': ['Organizar los resultados de una encuesta','Escribir editoriales en un periodico','Ensenar un oficio en una institucion para ninos de barrios pobres'],
	'Literario069': ['Organizar los resultados de una encuesta','Escribir editoriales en un periodico','Ensenar un oficio en una institucion para ninos de barrios pobres'],
	'ServicioSocial069': ['Organizar los resultados de una encuesta','Escribir editoriales en un periodico','Ensenar un oficio en una institucion para ninos de barrios pobres'],
	'Oficina069': ['Organizar los resultados de una encuesta','Escribir editoriales en un periodico','Ensenar un oficio en una institucion para ninos de barrios pobres'],
	'AireLibre060': ['Informarme mediante la lectura de las causas de diferentes enfermedades','Informarme de como los iniciadores de una industria alcanzaron exito','Informarme como criar ganado'],
	'Persuasivo060': ['Informarme mediante la lectura de las causas de diferentes enfermedades','Informarme de como los iniciadores de una industria alcanzaron exito','Informarme como criar ganado'],
	'ServicioSocial060': ['Informarme mediante la lectura de las causas de diferentes enfermedades','Informarme de como los iniciadores de una industria alcanzaron exito','Informarme como criar ganado'],
	

#Fila7


	'AireLibre071': ['Asistir a una reunion donde la mayor parte de la gente me es extrana','Estar en una reunion donde conozco a la mayoria de las personas','Asistir a una reunion compuesta igualmente por gente extrana y pobre'],
	'AireLibre072': ['Vender accesorios para trabajos artisticos','Cultivar semillas de flores','Criar conejillos de indias para los cientificos'],
	'Cientifico072': ['Vender accesorios para trabajos artisticos','Cultivar semillas de flores','Criar conejillos de indias para los cientificos'],
	'Persuasivo072': ['Vender accesorios para trabajos artisticos','Cultivar semillas de flores','Criar conejillos de indias para los cientificos'],
	'Cientifico073': ['Ejecutar experimentos de laboratorio','Hacer muebles','Ser vendedor de seguros'],
	'Persuasivo073': ['Ejecutar experimentos de laboratorio','Hacer muebles','Ser vendedor de seguros'],
	'Oficina074': ['Pesar los paquetes en correos para ver el valor que deben pagar','Leer los manuscritos admitidos para su publicacion','Probar automoviles nuevos para mejorarlos'],
	'Cientifico075': ['Ser un experto en cincelar joyas','Dirigir una investigacion para el desarrollo de un sustituto de la goma','Ser comentarista de musica en la radio'],
	'Musical075': ['Ser un experto en cincelar joyas','Dirigir una investigacion para el desarrollo de un sustituto de la goma','Ser comentarista de musica en la radio'],
	'Mecanico076': ['Ayudar en una enfermeria','Vender instrumentos musicales','Reparar aparatos domesticos'],
	'Persuasivo076': ['Ayudar en una enfermeria','Vender instrumentos musicales','Reparar aparatos domesticos'],
	'Musical076': ['Ayudar en una enfermeria','Vender instrumentos musicales','Reparar aparatos domesticos'],
	'ServicioSocial076': ['Ayudar en una enfermeria','Vender instrumentos musicales','Reparar aparatos domesticos'],
	'Cientifico077': ['Hacer disenos para floreros','Vigilar la manufactura de floreros','Trabajar en el desarrollo de una manera mas eficiente de hacer floreros'],
	'Persuasivo077': ['Hacer disenos para floreros','Vigilar la manufactura de floreros','Trabajar en el desarrollo de una manera mas eficiente de hacer floreros'],
	'Artistico077': ['Hacer disenos para floreros','Vigilar la manufactura de floreros','Trabajar en el desarrollo de una manera mas eficiente de hacer floreros'],
	'Mecanico078': ['Calcular las cuentas de los consumidores en una cafeteria','Ensenar aeromodelismo a los ninos','Archivar para un cientifico informes sobre investigaciones modicas'],
	'Cientifico078': ['Calcular las cuentas de los consumidores en una cafeteria','Ensenar aeromodelismo a los ninos','Archivar para un cientifico informes sobre investigaciones modicas'],
	'Oficina078': ['Calcular las cuentas de los consumidores en una cafeteria','Ensenar aeromodelismo a los ninos','Archivar para un cientifico informes sobre investigaciones modicas'],
	'Cientifico079': ['Dirigir los juegos en un patio de recreo a ninos deficientes','Ser cocinero en un restaurante','Vender productos quimicos'],
	'ServicioSocial079': ['Dirigir los juegos en un patio de recreo a ninos deficientes','Ser cocinero en un restaurante','Vender productos quimicos'],
	'Mecanico070': ['Reunir una coleccion de buenos instrumentos para trabajar en madera','Hacer un album de reproducciones de cuadros que gusten','Preparar un botiquin de urgencia'],
	

#Fila8

	'Literario081': ['Dirigir una compania de comedias de aficionados','Hacer imprimir las entradas y los programas para la presentacion','Escribir la comedia'],
	'Oficina081': ['Dirigir una compania de comedias de aficionados','Hacer imprimir las entradas y los programas para la presentacion','Escribir la comedia'],
	'Oficina082': ['Jugar a las damas con alguien que me gana frecuentemente','Jugar a las damas con alguien que casi nunca me gana','Jugar a las damas con alguien que tenga aproximadamente mi misma habilidad'],
	'Calculo083': ['Preparar la publicidad introductoria para una nueva lavadora','Determinar el costo de produccion de la lavadora','Vender lavadoras'],
	'Persuasivo083': ['Preparar la publicidad introductoria para una nueva lavadora','Determinar el costo de produccion de la lavadora','Vender lavadoras'],
	'AireLibre084': ['Escribir en la seccion de noticias locales de un periodico','Escribir en la seccion de consejos personales en un periodico','Escribir en la seccion dedicada a la jardineria en un periodico'],
	'AireLibre085': ['Ser explorador','Ser dibujante','Ser inventor'],
	'Cientifico085': ['Ser explorador','Ser dibujante','Ser inventor'],
	'AireLibre086': ['Recoger duraznos','Conducir tractor en una fabrica','Trabajar en un laboratorio quimico'],
	'Cientifico086': ['Recoger duraznos','Conducir tractor en una fabrica','Trabajar en un laboratorio quimico'],
	'Cientifico087': ['Seguir un curso de declamacion','Estudiar sociologia','Estudiar composicion literaria'],
	'Literario087': ['Seguir un curso de declamacion','Estudiar sociologia','Estudiar composicion literaria'],
	'Mecanico088': ['Hacer operaciones con una maquina de calcular','Reunir las diferentes partes de las maquinas calculadoras','Vender maquinas calculadoras'],
	'Calculo088': ['Hacer operaciones con una maquina de calcular','Reunir las diferentes partes de las maquinas calculadoras','Vender maquinas calculadoras'],
	'Persuasivo088': ['Hacer operaciones con una maquina de calcular','Reunir las diferentes partes de las maquinas calculadoras','Vender maquinas calculadoras'],
	'Oficina088': ['Hacer operaciones con una maquina de calcular','Reunir las diferentes partes de las maquinas calculadoras','Vender maquinas calculadoras'],
	'Mecanico089': ['Armar botes','Resolver cuestiones surgidas en el trabajo','Componer musica'],
	'Persuasivo089': ['Armar botes','Resolver cuestiones surgidas en el trabajo','Componer musica'],
	'Musical089': ['Armar botes','Resolver cuestiones surgidas en el trabajo','Componer musica'],
	'ServicioSocial089': ['Armar botes','Resolver cuestiones surgidas en el trabajo','Componer musica'],
	'Mecanico080': ['Ser el vendedor de tractores de mas exito del pais','Ser un contador publico de prestigio','Ser una autoridad en materia de costos de produccion'],
	'Calculo080': ['Ser el vendedor de tractores de mas exito del pais','Ser un contador publico de prestigio','Ser una autoridad en materia de costos de produccion'],
	'Persuasivo080': ['Ser el vendedor de tractores de mas exito del pais','Ser un contador publico de prestigio','Ser una autoridad en materia de costos de produccion'],
	



	#Fila9

	'ServicioSocial091': ['Desarrollar los metodos mas eficientes para trabajos de oficina','Tener gran experiencia en enfermeria','Tratar de perfeccionar los envases de'],
	'Oficina091': ['Desarrollar los metodos mas eficientes para trabajos de oficina','Tener gran experiencia en enfermeria','Tratar de perfeccionar los envases de'],
	'Mecanico092': ['Reparar la conexion de una plancha electrica','Encender el fuego en una chimenea','Escribir una carta a maquina a un amigo'],
	'Oficina092': ['Reparar la conexion de una plancha electrica','Encender el fuego en una chimenea','Escribir una carta a maquina a un amigo'],
	'Mecanico093': ['Dirigir un establecimiento de discos musicales','Trazar planos para edificios','Investigar acerca de las condiciones sociales en diferentes comunidades'],
	'Musical093': ['Dirigir un establecimiento de discos musicales','Trazar planos para edificios','Investigar acerca de las condiciones sociales en diferentes comunidades'],
	'ServicioSocial093': ['Dirigir un establecimiento de discos musicales','Trazar planos para edificios','Investigar acerca de las condiciones sociales en diferentes comunidades'],
	'Mecanico094': ['Descomponer un nuevo juguete mecanico para ver como funciona','Jugar damas','Jugar ajedrez'],
	'AireLibre095': ['Llevar los libros de contabilidad en un negocio','Desarrollar nuevas variedades de flores','Tratar con los demas sobre sus problemas personales'],
	'Oficina095': ['Llevar los libros de contabilidad en un negocio','Desarrollar nuevas variedades de flores','Tratar con los demas sobre sus problemas personales'],
	'ServicioSocial095': ['Llevar los libros de contabilidad en un negocio','Desarrollar nuevas variedades de flores','Tratar con los demas sobre sus problemas personales'],
	'AireLibre096': ['Pescar peces para un acuario','Seleccionar arboles que van a ser cortados en un bosque','Pintar los autos en una fabrica'],
	'Persuasivo097': ['Ser visitador social','Ser secretario de una persona famosa','Dirigir la propaganda comercial en una oficina de publicidad'],
	'ServicioSocial097': ['Ser visitador social','Ser secretario de una persona famosa','Dirigir la propaganda comercial en una oficina de publicidad'],
	'Oficina097': ['Ser visitador social','Ser secretario de una persona famosa','Dirigir la propaganda comercial en una oficina de publicidad'],
	'AireLibre098': ['Escribir una narracion sobre un hecho real para un periodico','Escribir un articulo sobre la cria de aves de corral','Escribir un articulo sobre primeros auxilios'],
	'Oficina099': ['Servir a los clientes en un restaurante','Buscar direcciones en una guia','Cuidar enfermos'],
	'Persuasivo090': ['Modelar arcilla','Escribir un articulo sobre el arte de convencer a la gente','Ser apuntador en una compania teatral de aficionados'],
	'Artistico090': ['Modelar arcilla','Escribir un articulo sobre el arte de convencer a la gente','Ser apuntador en una compania teatral de aficionados'],
	'Literario090': ['Modelar arcilla','Escribir un articulo sobre el arte de convencer a la gente','Ser apuntador en una compania teatral de aficionados'],
	

	#Fila 10
	'Cientifico101': ['Ser medico', 'Ser escultor', 'Ser periodista'],
	'Artistico101': ['Contestar a las cartas que pregunten sobre una nueva marca de maquinas', 'Recopilar los datos de ventas de maquinas de escribir', 'Tener las maquinas en orden para que las examinen los clientes'],
	'Literario101': ['Estudiar los metodos de propaganda utilizados en la guerra', 'Hacer un estudio de los metodos mas eficaces en oficina', 'Hacer un estudio sobre inmigracion'],
	'Mecanico102': ['Buscar los posibles errores en un borrador de informes', 'Lavar platos', 'Cocinar'],
	'Calculo102': ['Ser profesor de arquitectura', 'Visitar empresas solicitando anuncios de propaganda', 'Arreglar relojes'],
	'Oficina103': ['Cocinar', 'Arreglar un juguete roto', 'Lavar la cabeza a alguien con champu'],
	'Oficina104': ['Formar parte de una expedicion para buscar animales raros', 'Formar parte de una expedicion para combatir la epidemica', 'Realizar un trabajo de beneficencia social'],
	'Mecanico105': ['Ser pintor de retratos', 'Dirigir una investigacion sobre las causas de los terremotos', 'Ser ingeniero mecanico'],
	'Persuasivo105': ['Ayudar a la gente a organizar su presupuesto', 'Poner la etiqueta adecuada a los libros de una biblioteca', 'Ser un experto en el cuidado de los arboles'],
	'Artistico105': ['Vender en una gran tienda', 'Trabajar en una granja', 'Trabajar en una casa editora'],
	'Mecanico106': ['Ser medico', 'Ser escultor', 'Ser periodista'],
	'ServicioSocial107': ['Contestar a las cartas que pregunten sobre una nueva marca de maquinas', 'Recopilar los datos de ventas de maquinas de escribir', 'Tener las maquinas en orden para que las examinen los clientes'],
	'Mecanico108': ['Estudiar los metodos de propaganda utilizados en la guerra', 'Hacer un estudio de los metodos mas eficaces en oficina', 'Hacer un estudio sobre inmigracion'],
	'Artistico108': ['Buscar los posibles errores en un borrador de informes', 'Lavar platos', 'Cocinar'],
	'Cientifico108': ['Ser profesor de arquitectura', 'Visitar empresas solicitando anuncios de propaganda', 'Arreglar relojes'],
	'Calculo109': ['Cocinar', 'Arreglar un juguete roto', 'Lavar la cabeza a alguien con champu'],
	'Cientifico109': ['Formar parte de una expedicion para buscar animales raros', 'Formar parte de una expedicion para combatir la epidemica', 'Realizar un trabajo de beneficencia social'],
	'ServicioSocial109': ['Ser pintor de retratos', 'Dirigir una investigacion sobre las causas de los terremotos', 'Ser ingeniero mecanico'],
	'Oficina109': ['Ayudar a la gente a organizar su presupuesto', 'Poner la etiqueta adecuada a los libros de una biblioteca', 'Ser un experto en el cuidado de los arboles'],
	'Persuasivo100': ['Vender en una gran tienda', 'Trabajar en una granja', 'Trabajar en una casa editora'],
	'Oficina100': ['Ser medico', 'Ser escultor', 'Ser periodista'],
	

	#Fila 11
	'Calculo111': ['Ser profesor de matematicas', 'Ser director de publicidad para una gran universidad', 'Ser profesor de un idioma extranjero'],
	'Musical111': ['Seguir un curso de correspondencia comercial', 'Seguir un curso de tipografia (tecnicas de impresion)', 'Seguir un curso de ventas'],
	'Persuasivo111': ['Trazar planos de edificios', 'Informar por escrito la variacion de los costos', 'Escribir articulos sobre las nuevas ideas en la construccion'],
	'Persuasivo112': ['Comprar a plazos un articulo caro', 'Pedir prestado dinero a un amigo para comprar un articulo', 'Ahorrar hasta que pueda pagar el articulo al contado'],
	'Oficina112': ['Decorar muebles', 'Vigilar a los obreros en una plantacion de cana de azucar', 'Criar pavos'],
	'Persuasivo113': ['Ayudar a la gente joven a encontrar su vocacion', 'Disenar nuevos modelos de tejidos', 'Hacer calculos sobre el costo de impresion de libros'],
	'Persuasivo114': ['Construir un telar', 'Establecer formulas matematicas para predecir el curso de los negocios', 'Observar con fines de estudio las actitudes de los jovenes en la iglesia'],
	'AireLibre115': ['Hacer una mascarilla de yeso de una persona viva', 'Escribir un articulo sobre como los comerciantes fijan el alza de precios', 'Componer la letra de una cancion para un programa de radio'],
	'Calculo116': ['Probar las diferentes marcas de un producto para ver cual es la mejor que se puede ofrecer', 'Estar a cargo del Boletin de informacion en una gran organizacion', 'Mantener en un buen estado las maquinas computadoras'],
	'Artistico116': ['Tener gente a mi alrededor que me trata como a un igual', 'Tener gente a mi alrededor que me trata como superior', 'Tener gente a mi alrededor que no me preste atencion'],
	'Mecanico117': ['Ser profesor de matematicas', 'Ser director de publicidad para una gran universidad', 'Ser profesor de un idioma extranjero'],
	'Calculo117': ['Seguir un curso de correspondencia comercial', 'Seguir un curso de tipografia (tecnicas de impresion)', 'Seguir un curso de ventas'],
	'Calculo118': ['Trazar planos de edificios', 'Informar por escrito la variacion de los costos', 'Escribir articulos sobre las nuevas ideas en la construccion'],
	'Artistico118': ['Comprar a plazos un articulo caro', 'Pedir prestado dinero a un amigo para comprar un articulo', 'Ahorrar hasta que pueda pagar el articulo al contado'],
	'Mecanico119': ['Decorar muebles', 'Vigilar a los obreros en una plantacion de cana de azucar', 'Criar pavos'],
	'Calculo119': ['Ayudar a la gente joven a encontrar su vocacion', 'Disenar nuevos modelos de tejidos', 'Hacer calculos sobre el costo de impresion de libros'],
	'Calculo110': ['Construir un telar', 'Establecer formulas matematicas para predecir el curso de los negocios', 'Observar con fines de estudio las actitudes de los jovenes en la iglesia'],
	

	#Fila 12
	'Artistico121': ['Ser profesor de musica', 'Realizar la parte artistica en una agencia de publicidad', 'Dirigir una investigacion para hallar las razones de la gracia en los chistes'],
	'Mecanico122': ['Ir de compras en lugar de una persona enferma', 'Hacer un rompecabezas para distraer a una persona enferma', 'Leer en voz alta a un enfermo'],
	'Oficina123': ['Ayudar en las curas de urgencia de un hospital', 'Ser vendedor de mostrador en una tienda de flores', 'Ser secretario privado'],
	'Persuasivo124': ['Llevar la pagina financiera de un periodico', 'Poner en marcha el cultivo de un terreno virgen', 'Vender bienes inmuebles'],
	'Literario124': ['Prestar asistencia a sordos', 'Trazar graficos basados en datos estadisticos', 'Estar empleado en las oficinas de una gran tienda'],
	'Persuasivo125': ['Ser escritor', 'Ser una autoridad en propaganda comercial', 'Ser un lider religioso'],
	'ServicioSocial125': ['Realizar un trabajo que sea de mi agrado y este bien renumerado', 'Realizar un trabajo que sea de mi agrado y este mal renumerado', 'Realizar un trabajo que no sea de mi agrado y este bien renumerado'],
	'Literario125': ['Ensenar a los asistidos por la beneficencia publica a conservar la salud', 'Escribir articulos de fondo a editoriales para un periodico', 'Negociar objetos de arte'],
	'Persuasivo126': ['Ser secretario de un diputado o senador', 'Ensenar dibujo y modelado a ninos', 'Escribir articulos para una revista de arte'],
	'Artistico128': ['Elegir mi ropa por mi mismo', 'Dejarme aconsejar al elegir mi ropa', 'Dejar que alguien elija mi ropa'],
	'Literario128': ['Ser profesor de musica', 'Realizar la parte artistica en una agencia de publicidad', 'Dirigir una investigacion para hallar las razones de la gracia en los chistes'],
	'ServicioSocial128': ['Ir de compras en lugar de una persona enferma', 'Hacer un rompecabezas para distraer a una persona enferma', 'Leer en voz alta a un enfermo'],
	'Artistico129': ['Ayudar en las curas de urgencia de un hospital', 'Ser vendedor de mostrador en una tienda de flores', 'Ser secretario privado'],
	'Literario129': ['Llevar la pagina financiera de un periodico', 'Poner en marcha el cultivo de un terreno virgen', 'Vender bienes inmuebles'],
	'Oficina129': ['Prestar asistencia a sordos', 'Trazar graficos basados en datos estadisticos', 'Estar empleado en las oficinas de una gran tienda'],
	'Oficina120': ['Ser escritor', 'Ser una autoridad en propaganda comercial', 'Ser un lider religioso'],
	
	# Fila 13
	'Mecanico131': ['Proyectar planos para construir puentes', 'Realizar trabajos que requieren de operaciones aritmeticas', 'Realizar un trabajo en una oficina publica'],
	'Calculo131': ['Inspeccionar la manufactura de tarjetas de felicitacion', 'Determinar el costo de produccion de tarjetas de felicitacion', 'Disenar tarjetas de felicitacion'],
	'Oficina131': ['Desarmar una cerradura para ver que es lo que funciona mal en ella', 'Examinar los errores en la copia de un informe', 'Sumar columnas de numeros'],
	'Calculo132': ['Tener cerca de mi a alguien que me haga parecer tonto', 'Hacer a alguien que parezca tonto', 'No dejar que nadie me haga parecer tonto, ni yo tampoco hacer que alguien parezca tonto'],
	'Artistico132': ['Tener la profesion de psicologo', 'Vigilar la construccion de puentes', 'Ser arquitecto paisajista'],
	'Mecanico133': ['Investigar las causas de las enfermedades mentales', 'Dedicarme al estudio de arreglos musicales', 'Estudiar taquigrafia'],
	'Calculo133': ['Ser chofer en la ciudad', 'Ser guardian en una granja', 'Cuidar rieles en un ferrocarril'],
	'Oficina133': ['Redactar anuncios o propagandas', 'Estar a cargo de una biblioteca publica', 'Publicar un periodico'],
	'Mecanico134': ['Seguir un curso de teneduria de libros', 'Seguir un curso sobre el arte de vender', 'Seguir un curso de correspondencia comercial'],
	'Calculo134': ['Escribir una comedia', 'Estar a cargo de la venta de entradas para una funcion', 'Ser el director de la comedia'],
	'Mecanico135': ['Proyectar planos para construir puentes', 'Realizar trabajos que requieren de operaciones aritmeticas', 'Realizar un trabajo en una oficina publica'],
	'Cientifico135': ['Inspeccionar la manufactura de tarjetas de felicitacion', 'Determinar el costo de produccion de tarjetas de felicitacion', 'Disenar tarjetas de felicitacion'],
	'Artistico135': ['Desarmar una cerradura para ver que es lo que funciona mal en ella', 'Examinar los errores en la copia de un informe', 'Sumar columnas de numeros'],
	'AireLibre136': ['Tener cerca de mi a alguien que me haga parecer tonto', 'Hacer a alguien que parezca tonto', 'No dejar que nadie me haga parecer tonto, ni yo tampoco hacer que alguien parezca tonto'],
	'Cientifico136': ['Tener la profesion de psicologo', 'Vigilar la construccion de puentes', 'Ser arquitecto paisajista'],
	'Musical136': ['Investigar las causas de las enfermedades mentales', 'Dedicarme al estudio de arreglos musicales', 'Estudiar taquigrafia'],
	'Persuasivo138': ['Ser chofer en la ciudad', 'Ser guardian en una granja', 'Cuidar rieles en un ferrocarril'],
	'Calculo139': ['Redactar anuncios o propagandas', 'Estar a cargo de una biblioteca publica', 'Publicar un periodico'],
	'Persuasivo139': ['Seguir un curso de teneduria de libros', 'Seguir un curso sobre el arte de vender', 'Seguir un curso de correspondencia comercial'],
	'Literario130': ['Escribir una comedia', 'Estar a cargo de la venta de entradas para una funcion', 'Ser el director de la comedia'],
	'Oficina130': ['Proyectar planos para construir puentes', 'Realizar trabajos que requieren de operaciones aritmeticas', 'Realizar un trabajo en una oficina publica'],
	

	# Fila 14
	'AireLibre141': ['Hacer caricaturas de gente famosa', 'Pintar retratos de gente famosa', 'Pintar paisajes'],
	'Artistico142': ['Hacer ilustraciones para revistas', 'Escribir articulos para revistas', 'Ser el director de ventas de una revista'],
	'Literario142': ['Pasar una temporada en un lugar de verano que este de moda', 'Hacer camping', 'Hacer una excursion por carretera a un punto lejano de la ciudad'],
	'AireLibre143': ['Vivir con un famoso critico dramatico', 'Vivir con un famoso psicologo', 'Vivir con un famoso artista'],
	'AireLibre144': ['Escribir articulos sobre hobbies', 'Hacer tablas numericas sobre el costo de vida', 'Reparar y retocar el mobiliario desgastado'],
	'Mecanico145': ['Corregir pruebas de imprenta de libros para ninos', 'Contar cuentos a los ninos', 'Hacer juguetes'],
	'ServicioSocial146': ['Seguir un curso de educacion fisica', 'Seguir un curso sobre comercio', 'Seguir un curso sobre matematicas'],
	'Mecanico146': ['Ser afinador de pianos', 'Ser maestro de escuela', 'Ser dentista'],
	'Oficina146': ['Ser taquigrafo en una oficina publica', 'Ser el agente o representante comercial de un pianista famoso', 'Ser orientador profesional'],
	'Calculo147': ['Visitar un museo de historia natural', 'Visitar un taller de reparacion de aviones', 'Visitar los barrios pobres o pueblos jovenes de una ciudad'],
	'Mecanico147': ['Hacer caricaturas de gente famosa', 'Pintar retratos de gente famosa', 'Pintar paisajes'],
	'Oficina148': ['Hacer ilustraciones para revistas', 'Escribir articulos para revistas', 'Ser el director de ventas de una revista'],
	'Musical149': ['Pasar una temporada en un lugar de verano que este de moda', 'Hacer camping', 'Hacer una excursion por carretera a un punto lejano de la ciudad'],
	'ServicioSocial149': ['Vivir con un famoso critico dramatico', 'Vivir con un famoso psicologo', 'Vivir con un famoso artista'],
	'Mecanico140': ['Escribir articulos sobre hobbies', 'Hacer tablas numericas sobre el costo de vida', 'Reparar y retocar el mobiliario desgastado'],
	'ServicioSocial140': ['Corregir pruebas de imprenta de libros para ninos', 'Contar cuentos a los ninos', 'Hacer juguetes'],
	
	# Fila 15
	'AireLibre151': ['Hacer los dibujos para los cuentos de una revista', 'Dedicarme a la cria de ganado', 'Cultivar frutas para el consumo publico'],
	'AireLibre152': ['Ser botones de un hotel', 'Secar platos en un hotel', 'Vivir solo en una isla'],
	'AireLibre153': ['Ser guia de excursionistas', 'Hacer los planos de un campamento', 'Vender equipos de campamentos'],
	'Persuasivo153': ['Ser agente de seguros', 'Escribir cuentos para revistas', 'Ser jardinero'],
	'AireLibre154': ['Ser conocido como persona modesta', 'Ser conocido como persona veraz', 'Ser conocido como persona atolondrada'],
	'Persuasivo154': ['Ensenar aritmetica', 'Entrenar perros para lazarillos de ciegos', 'Ser el secretario de un cientifico famoso'],
	'Literario154': ['Seguir un curso de musica moderna', 'Seguir un curso sobre novela moderna', 'Seguir un curso sobre pintura moderna'],
	'AireLibre155': ['Ser considerado testarudo', 'Ser considerado razonable', 'Ser considerado inteligente'],
	'Calculo156': ['Ser director de orquesta', 'Ser director de una oficina', 'Dirigir los proyectos de ayuda de beneficencia a un barrio pobre'],
	'Oficina156': ['Cultivar flores', 'Manejar una fotocopiadora', 'Sumar notas de venta en una tienda'],
	'AireLibre157': ['Hacer los dibujos para los cuentos de una revista', 'Dedicarme a la cria de ganado', 'Cultivar frutas para el consumo publico'],
	'Artistico157': ['Ser botones de un hotel', 'Secar platos en un hotel', 'Vivir solo en una isla'],
	'Literario157': ['Ser guia de excursionistas', 'Hacer los planos de un campamento', 'Vender equipos de campamentos'],
	'AireLibre158': ['Ser agente de seguros', 'Escribir cuentos para revistas', 'Ser jardinero'],
	'ServicioSocial158': ['Ser conocido como persona modesta', 'Ser conocido como persona veraz', 'Ser conocido como persona atolondrada'],
	'AireLibre159': ['Ensenar aritmetica', 'Entrenar perros para lazarillos de ciegos', 'Ser el secretario de un cientifico famoso'],
	'Oficina159': ['Seguir un curso de musica moderna', 'Seguir un curso sobre novela moderna', 'Seguir un curso sobre pintura moderna'],
	'Musical159': ['Ser considerado testarudo', 'Ser considerado razonable', 'Ser considerado inteligente'],
	'Mecanico150': ['Ser director de orquesta', 'Ser director de una oficina', 'Dirigir los proyectos de ayuda de beneficencia a un barrio pobre'],
	'Calculo150': ['Cultivar flores', 'Manejar una fotocopiadora', 'Sumar notas de venta en una tienda'],
	'Oficina150': ['Hacer los dibujos para los cuentos de una revista', 'Dedicarme a la cria de ganado', 'Cultivar frutas para el consumo publico'],
	
		#Fila 16
	'Oficina161': ['Ser guia en un parque nacional', 'Trabajar en una joyeria fina', 'Arreglar musica para orquesta'],
	'Mecanico162': ['Trabajar como telefonista', 'Hacer sellos de goma', 'Ensenar juegos a los ninos'],
	'ServicioSocial162': ['Arreglar una tabla de planchar', 'Lavar platos', 'Ordenar una habitacion'],
	'Oficina162': ['Ensenar a hacer canastas de paja', 'Corregir pruebas para un periodico', 'Importar alfombras orientales'],
	'Mecanico163': ['Ser secretario particular', 'Ser tenedor de libros', 'Ser vendedor'],
	'Oficina164': ['Hacer patinaje artistico', 'Jugar al polo', 'Escalar montanas'],
	'Oficina165': ['Trabajar en un estudio de abogados', 'Trabajar en una granja', 'Vender de casa en casa'],
	'Persuasivo165': ['Trabajar en una fabrica de caramelos', 'Ser apicultor (criador de abejas)', 'Dedicarme a medir la vista de las personas'],
	'AireLibre166': ['Ser granjero', 'Ser conductor de un tren', 'Ser oficinista'],
	'Persuasivo167': ['Realizar un trabajo administrativo', 'Ensenar literatura', 'Vender material para trabajo artistico'],
	'Oficina167': ['Ser guia en un parque nacional', 'Trabajar en una joyeria fina', 'Arreglar musica para orquesta'],
	'Oficina168': ['Trabajar como telefonista', 'Hacer sellos de goma', 'Ensenar juegos a los ninos'],
	'Oficina169': ['Arreglar una tabla de planchar', 'Lavar platos', 'Ordenar una habitacion'],
	'Persuasivo160': ['Ensenar a hacer canastas de paja', 'Corregir pruebas para un periodico', 'Importar alfombras orientales'],
	'Artistico160': ['Ser secretario particular', 'Ser tenedor de libros', 'Ser vendedor'],
	'Literario160': ['Hacer patinaje artistico', 'Jugar al polo', 'Escalar montanas'],
	'Oficina160': ['Trabajar en un estudio de abogados', 'Trabajar en una granja', 'Vender de casa en casa'],
	
	# Fila 17
	'AireLibre171': ['Estudiar Contabilidad', 'Estudiar metodos de irrigacion agricola', 'Estudiar taquigrafia'],
	'Calculo171': ['Repartir el correo', 'Recoger la basura', 'Ordenar las cartas en una oficina de correos'],
	'Oficina171': ['Ser poeta', 'Ser artista', 'Ser asistente social'],
	'Oficina172': ['Realizar juegos matematicos', 'Jugar a las damas', 'Hacer rompecabezas mecanicos'],
	'Artistico173': ['Organizar un periodico', 'Organizar una escuela de arte', 'Organizar una orquesta'],
	'ServicioSocial173': ['Tener amigos', 'Tener poder', 'Tener fama'],
	'Calculo174': ['Ser maquinista', 'Ser arquitecto', 'Ser quimico'],
	'Mecanico174': ['Encuadernar libros', 'Cuidar ninos enfermos', 'Escribir cartas a maquina'],
	'Artistico175': ['Estudiar Contabilidad', 'Estudiar metodos de irrigacion agricola', 'Estudiar taquigrafia'],
	'Musical175': ['Repartir el correo', 'Recoger la basura', 'Ordenar las cartas en una oficina de correos'],
	'Oficina176': ['Ser poeta', 'Ser artista', 'Ser asistente social'],
	'Cientifico177': ['Realizar juegos matematicos', 'Jugar a las damas', 'Hacer rompecabezas mecanicos'],
	'Artistico177': ['Organizar un periodico', 'Organizar una escuela de arte', 'Organizar una orquesta'],
	'Mecanico177': ['Tener amigos', 'Tener poder', 'Tener fama'],
	'ServicioSocial178': ['Ser maquinista', 'Ser arquitecto', 'Ser quimico'],
	'Mecanico178': ['Encuadernar libros', 'Cuidar ninos enfermos', 'Escribir cartas a maquina'],
	'Oficina178': ['Estudiar Contabilidad', 'Estudiar metodos de irrigacion agricola', 'Estudiar taquigrafia'],
	
}

# Identificar preguntas repetidas
preguntas_repetidas = {

	# Lista1
	'Persuasivo012': 'Calculo012',
	'ServicioSocial012': 'Calculo012',
	'Persuasivo018': 'AireLibre018',
	'Musical018': 'AireLibre018',
	'Cientifico010': 'Mecanico010',
	'Persuasivo010': 'Mecanico010',
	
	# Lista2
	'Artistico022': 'Mecanico022',
	'Artistico024': 'Mecanico024',
	'Musical024': 'Mecanico024',
	'Persuasivo027': 'AireLibre027',
	'Oficina020': 'AireLibre020',
	'Cientifico020': 'AireLibre020',
	
	# Lista3
	'ServicioSocial033': 'Persuasivo033',
	'Artistico035': 'Persuasivo035',
	'Artistico036': 'Cientifico036',
	'Musical037': 'Cientifico037',
	'Oficina037': 'Cientifico037',
	'Musical038': 'Cientifico038',
	'Oficina039': 'Persuasivo039',
	
	# ANDREA
	# Lista4
	'Literario044': 'Cientifico044',
	'ServicioSocial044': 'Cientifico044',
	'Oficina046': 'ServicioSocial046',
	'ServicioSocial047': 'Cientifico047',
	'Oficina047': 'Cientifico047',
	'ServicioSocial048': 'Cientifico048',
	'ServicioSocial040': 'Cientifico040',
	'Oficina040': 'Cientifico040',
	


	# Lista5
	'Musical051': 'Cientifico051',
	'Oficina052': 'Cientifico052',
	'Literario055': 'Persuasivo055',
	'Oficina055': 'Persuasivo055',
	'Oficina056': 'Literario056',
	'Persuasivo058': 'AireLibre058',
	'Oficina058': 'AireLibre058',
	'Literario059': 'Cientifico059',
	'ServicioSocial059': 'Cientifico059',
	
	# Lista6
	'Persuasivo061': 'Cientifico061',
	'ServicioSocial061': 'Cientifico061',
	'Oficina061': 'Cientifico061',
	'Oficina062': 'Persuasivo062',
	'Persuasivo063': 'AireLibre063',
	'Artistico063': 'AireLibre063',
	'Artistico064': 'Cientifico064',
	'ServicioSocial064': 'Cientifico064',
	'Oficina065': 'Cientifico065',
	'Cientifico066': 'Mecanico066',
	'Artistico066': 'Mecanico066',
	'Persuasivo067': 'Calculo067',
	'Persuasivo068': 'Calculo068',
	'ServicioSocial068': 'Calculo068',
	'Literario069': 'Calculo069',
	'ServicioSocial069': 'Calculo069',
	'Oficina069': 'Calculo069',
	'Persuasivo060': 'AireLibre060',
	'ServicioSocial060': 'AireLibre060',
	
	# Lista7
	'Cientifico072': 'AireLibre072',
	'Persuasivo072': 'AireLibre072',
	'Persuasivo073': 'Cientifico073',
	'Musical075': 'Cientifico075',
	'Persuasivo076': 'Mecanico076',
	'Musical076': 'Mecanico076',
	'ServicioSocial076': 'Mecanico076',
	'Persuasivo077': 'Cientifico077',
	'Artistico077': 'Cientifico077',
	'Cientifico078': 'Mecanico078',
	'Oficina078': 'Mecanico078',
	'ServicioSocial079': 'Cientifico079',
	
	# Lista8
	'Oficina081': 'Literario081',
	'Persuasivo083': 'Calculo083',
	'Cientifico085': 'AireLibre085',
	'Cientifico086': 'AireLibre086',
	'Literario087': 'Cientifico087',
	'Calculo088': 'Mecanico088',
	'Persuasivo088': 'Mecanico088',
	'Oficina088': 'Mecanico088',
	'Persuasivo089': 'Mecanico089',
	'Musical089': 'Mecanico089',
	'ServicioSocial089': 'Mecanico089',
	'Calculo080': 'Mecanico080',
	'Persuasivo080': 'Mecanico080',
	

	# Lista9
	'Oficina091': 'ServicioSocial091',
	'Oficina092': 'Mecanico092',
	'Musical093': 'Mecanico093',
	'ServicioSocial093': 'Mecanico093',
	'ServicioSocial095': 'Oficina095',
	'ServicioSocial097': 'Persuasiv0097',
	'Oficina097': 'Persuasiv0097',
	'Artistico090': 'Persuasivo090',
	'Literario090': 'Persuasivo090',
	
	# Lista10
	'Artistico101': 'Cientifico101',
	'Literario101': 'Cientifico101',
	'Calculo102': 'Mecanico102',
	'Persuasivo105': 'Mecanico105',
	'Artistico105': 'Mecanico105',
	'Artistico108': 'Mecanico108',
	'Cientifico108': 'Mecanico108',
	'Cientifico109': 'Calculo109',
	'ServicioSocial109': 'Calculo109',
	'Oficina109': 'Calculo109',
	'Oficina100': 'Persuasivo100',
	
	# Lista11
	'Musical111': 'Calculo111',
	'Persuasivo111': 'Calculo111',
	'Oficina112': 'Persuasivo112',
	'Artistico116': 'Calculo116',
	'Calculo117': 'Mecanico117',
	'Artistico118': 'Calculo118',
	'Calculo119': 'Mecanico119',
	
	# Lista12
	'Literario124': 'Persuasivo124',
	'ServicioSocial125': 'Persuasivo125',
	'Literario125': 'Persuasivo125',
	'Literario128': 'Artistico128',
	'ServicioSocial128': 'Artistico128',
	'Literario129': 'Artistico129',
	'Oficina129': 'Artistico129',
	
	# Lista13
	'Calculo131': 'Mecanico131',
	'Oficina131': 'Mecanico131',
	'Artistico132': 'Calculo132',
	'Calculo133': 'Mecanico133',
	'Oficina133': 'Mecanico133',
	'Calculo134': 'Mecanico134',
	'Cientifico135': 'Mecanico135',
	'Artistico135': 'Mecanico135',
	'Cientifico136': 'AireLibre136',
	'Musical136': 'AireLibre136',
	'Persuasivo139': 'Calculo139',
	'Oficina130': 'Literario130',
	

	# Lista14
	'Literario142': 'Artistico142',
	'Mecanico146': 'ServicioSocial146',
	'Oficina146': 'ServicioSocial146',
	'Mecanico147': 'Calculo147',
	'ServicioSocial149': 'Musical149',
	'ServicioSocial140': 'Mecanico140',
	
	# Lista15
	'Persuasivo153': 'AireLibre153',
	'Persuasivo154': 'AireLibre154',
	'Literario154': 'AireLibre154',
	'Oficina156': 'Calculo156',
	'Artistico157': 'AireLibre157',
	'Literario157': 'AireLibre157',
	'ServicioSocial158': 'AireLibre158',
	'Oficina159': 'AireLibre159',
	'Musical159': 'AireLibre159',
	'Calculo150': 'Mecanico150',
	'Oficina150': 'Mecanico150',
	
	# Lista16
	'ServicioSocial162': 'Mecanico162',
	'Oficina162': 'Mecanico162',
	'Persuasivo165': 'Oficina165',
	'Oficina167': 'Persuasivo167',
	'Artistico160': 'Persuasivo160',
	'Literario160': 'Persuasivo160',
	'Oficina160': 'Persuasivo160',
	
	# Lista17
	'Calculo171': 'AireLibre171',
	'Oficina171': 'AireLibre171',
	'ServicioSocial173': 'Artistico173',
	'Mecanico174': 'Calculo174',
	'Musical175': 'Artistico175',
	'Artistico177': 'Cientifico177',
	'Mecanico177': 'Cientifico177',
	'Mecanico178': 'ServicioSocial178',
	'Oficina178': 'ServicioSocial178',
	

}


respuestas_repetidas = {}


respuestas_areas = {}